### ISSUE TITLE
Question on management of app/net keys

### ISSUE THREAD

**Issue by sbrown4** [SilvairGit/python-bluetooth-mesh#47]
It looks like your package currently manages these. There is also functionality in the mesh daemon to create and manage them as well. Going forward, do you plan to keep your functionality and add a persistent store or use the mesh daemon?

**Comment by michallowasrzechonek-silvair** [comment]
Well, they are separate things really.

What you're describing here is the 'provisioning database' - that is, a db with complete information about provisioned network, with all the keys, all the addresses etc. The daemon itself does *not* need access to the full database. There are two cases in play:

1. The daemon is a regular non-provisioner node
In this case, it needs only a subset of it, and keeps that in its internal storage (think: keyring). Not that the *value* of keys is never exposed to the application, and the keys can be loaded from the air. The application only knows key indexes and model bindings.

2. The daemon *is* a provisioner
In this mode, even though the daemon does have all the needed info, there is no 'official' API to export a full provisioning database from it. To make matters worse, if you use `AddNode()` API, the value of the device key derived during provisioning *will not* be exposed to the application. This is problematic, because such a database *really* should be backed up somewhere.

In the end, since the mesh spec does not say how are you supposed to deal with the provisioning db, so we figured this needs to happen on the application side.

At the moment we're not using the daemon as provisioner, we have a dedicated Commissioning Platform for that that keeps everything in the cloud. For this reason, `bluetooth-mesh` does not implement a local database yet, although it's certainly possible to add it.

I've started thinking about that in #40, but right now I don't have enough time to finalize it, sorry :(

**Comment by sbrown4** [comment]
Thanks for the explanation. I agree with your assessment of the daemon's database.

I've been using your package for provisioning via `AddNode()` and `AddAppKey().` In the short term, the daemon's database is sufficient for my purposes.

Even being new to Python, `bluetooth-mesh` is orders of magnitude easier to extend than `mesh-cfgclient.`
